name: george_ikwegbu_mobile
description: George Ikwegbu â€” Personal portfolio WebView app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.4.3
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2
  fake_async: ^1.3.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#00B4FF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter_native_splash:
  color: "#00B4FF"
  fullscreen: true
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
